# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Json2hcl < Formula
  desc "A tool to convert JSON to HCL."
  homepage "https://github.com/winebarrel/json2hcl"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/json2hcl/releases/download/v0.1.0/json2hcl_0.1.0_darwin_amd64.tar.gz"
      sha256 "3d82b9c11b50398db212ce16c5d72930809948005dea2f314b18c80730fcd2c2"

      def install
        bin.install 'json2hcl'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/json2hcl/releases/download/v0.1.0/json2hcl_0.1.0_darwin_arm64.tar.gz"
      sha256 "70d2c8616f82e601b1cffc6c54305b5a65fbb430757e7baeb907151cecf1719a"

      def install
        bin.install 'json2hcl'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/json2hcl/releases/download/v0.1.0/json2hcl_0.1.0_linux_arm64.tar.gz"
      sha256 "5552ba7cd882eb87e158641882d32fb9e46ac3a6f32213f5c6e67c2faecb8db9"

      def install
        bin.install 'json2hcl'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/json2hcl/releases/download/v0.1.0/json2hcl_0.1.0_linux_amd64.tar.gz"
      sha256 "72b1db767fff80670cf44d07f4bf6f20e0091a78f1325fe72396bcf587c651e7"

      def install
        bin.install 'json2hcl'
      end
    end
  end
end
