# This file was generated by GoReleaser. DO NOT EDIT.
cask "json2hcl" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "a95f2d66d416708378b7b8b1e071a543ea3c5e85fbd3bc2f3f213b136da15402"
      url "https://github.com/winebarrel/json2hcl/releases/download/v#{version}/json2hcl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ed5e9e3180e90d8ab736ef0e05577d1923178970f66b1f30a7e93ad3b9feff67"
      url "https://github.com/winebarrel/json2hcl/releases/download/v#{version}/json2hcl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d30870730b59f7f55a5831a282850c986ee65d4820bbff7dd0c1c31a4343f2bb"
      url "https://github.com/winebarrel/json2hcl/releases/download/v#{version}/json2hcl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7c238f7fc431a35e5bfb2c3d5a5aa309bf5efb34803decf84c12d0e2549e4419"
      url "https://github.com/winebarrel/json2hcl/releases/download/v#{version}/json2hcl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "json2hcl"
  desc "A tool to convert JSON to HCL."
  homepage "https://github.com/winebarrel/json2hcl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "json2hcl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/json2hcl"]
    end
  end

  # No zap stanza required

end
